;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        counsel-M-x
        counsel-git
        counsel-git-grep
        counsel-grep-or-swiper
        helm-M-x
        hungry-delete-backward
        ivy-done
        ivy-switch-buffer
        mouse-set-region
        swiper
        swiper-mc
        ))
